Repository Career-Bootcamps/OpenCV-OCR-Translate, pull requests merged in 2024-07, with the labels that each got.

#6 sample: filedialog 사용 예시 추가
  sample/yunjeong/filedialog_practice.py
Labels: documentation

#7 쓰기 tab 디스플레이 분할 해결-2
  oot/gui/gui_main.py
  sample/jiwon/tab_gui.py
Labels: enhancement

#16 issue-#11 OUTPUT_FILES 폴더 생성 및 이미지 복사 기능 구현 완료
  oot/data/data_manager.py
Labels: enhancement

#19 issue-#9 폴더 변경시 상세경로 표시 버그 수정 완료
  oot/control/top_control.py
  oot/data/data_manager.py
  oot/gui/top_frame.py
Labels: bug

#22 issue-#13 middle 영역 우측 이미지를 output_files 폴더의 이미지로 교체
  oot/data/data_manager.py
  oot/gui/middle_frame.py
Labels: enhancement

#24 Writing tab split screen layout
  oot/control/low_write_control.py
  oot/gui/low_frame.py
  oot/gui/middle_frame.py
Labels: enhancement

#26 issue-#20 폴더 변경 시 middle 이미지 교체 기능 수정 완료
  oot/control/top_control.py
Labels: bug

#31 Ignore output files
  .gitignore
Labels: bug

#33 Add: #12 conflict 해결 - 포지션 변수 추가수정 및 get_text_data 함수추가
  oot/data/data_manager.py
Labels: enhancement

#43 issue-#30 feat: top_frame에 저장하기 버튼 추가 및 기능 구현
  oot/control/top_control.py
  oot/data/data_manager.py
  oot/gui/top_frame.py
Labels: enhancement

#53 #50 기존 low_frame에 구현되었던 기능을 write_frame파일로 분할
  oot/gui/low_frame.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#52 issue-#44 feat: low_frame에 지우기탭 UI layout 구현
  oot/gui/low_frame.py
  oot/gui/subframes/remove_frame.py
Labels: enhancement

#64 fix: #54 쓰기 탭 변경시 에러 수정
  oot/gui/low_frame.py
Labels: bug

#66 refactor: #63 low_frame 코드 리팩토링
  oot/gui/low_frame.py
  oot/gui/subframes/common.py
  oot/gui/subframes/remove_frame.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#71 Datamanager code refactoring
  oot/control/top_control.py
  oot/data/data_manager.py
  oot/gui/middle_frame.py
  oot/gui/top_frame.py
Labels: enhancement

#83 Prev img error
  oot/control/top_control.py
  oot/data/data_manager.py
Labels: bug

#85 chore: #80 데이터매니저 구조 변경
  oot/control/top_control.py
  oot/data/data_manager.py
  oot/gui/middle_frame.py
  oot/gui/top_frame.py
Labels: enhancement

#89 issue-#45 feat: remove_tab 텍스트 찾기 버튼 클릭 시 ocr 수행 및 DataManager 업데이트
  oot/control/low_remove_control.py
  oot/data/data_manager.py
  oot/gui/subframes/remove_frame.py
Labels: enhancement

#91 Write tab ocr
  oot/control/low_write_control.py
  oot/control/top_control.py
  oot/data/data_manager.py
  oot/gui/subframes/common.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#94 doc: #93 데이터매니저 uml 문서 추가
  doc/class_datamanager.puml
Labels: documentation

#96 feat: #46 remove_tab ocr 수행 결과를 바탕으로 화면에 text 출력
  oot/control/low_remove_control.py
  oot/control/top_control.py
  oot/data/data_manager.py
  oot/gui/gui_main.py
  oot/gui/low_frame.py
  oot/gui/subframes/common.py
  oot/gui/subframes/mosaic_frame.py
  oot/gui/subframes/remove_frame.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#101 Write scrollhandler
  oot/control/low_write_control.py
  oot/gui/subframes/common.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#104 Display checked text
  oot/control/low_write_control.py
  oot/gui/low_frame.py
  oot/gui/subframes/common.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#106 fix: #105 텍스트 읽어오기와 동시에 번역실행
  oot/control/low_write_control.py
  oot/gui/subframes/common.py
  oot/gui/subframes/write_frame.py
Labels: bug

#109 Prev ocr data 2
  oot/control/low_write_control.py
  oot/data/data_manager.py
  oot/gui/gui_main.py
  oot/gui/low_frame.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#102 feat: #47 remove_tab 텍스트 체크시 양쪽 이미지에 해당 텍스트 영역 사각형 표시
  oot/control/low_remove_control.py
  oot/data/data_manager.py
  oot/gui/middle_frame.py
Labels: enhancement

#111 feat: #48 remove_tab 선택된 텍스트 지우기
  oot/control/low_remove_control.py
  oot/data/data_manager.py
  oot/gui/middle_frame.py
  oot/gui/subframes/remove_frame.py
Labels: enhancement

#112 Refine texts tool
  oot/data/data_manager.py
  oot/gui/low_frame.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#114 add: #39 - write탭 상자 그리기
  oot/control/low_write_control.py
  oot/gui/low_frame.py
  oot/gui/middle_frame.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#117 creat: #36 brightness 조절 및 image 에 적용
  oot/gui/subframes/edit_frame.py
Labels: enhancement

#126 issue - #122 캔버스 워커 모듈화
  oot/control/low_remove_control.py
  oot/control/low_write_control.py
  oot/gui/common.py
  oot/gui/middle_frame.py
  oot/gui/subframes/mosaic_frame.py
  oot/gui/subframes/remove_frame.py
  oot/gui/subframes/write_frame.py
Labels: enhancement

#129 fix: #128 탭인덱스에 따른 do_post_draw() 실행
  oot/control/low_remove_control.py
  oot/control/low_write_control.py
  oot/gui/subframes/remove_frame.py
Labels: bug

#130 feat: #49 remove_tab 원상태 복원 기능 구현
  oot/control/low_remove_control.py
  oot/gui/middle_frame.py
  oot/gui/subframes/remove_frame.py
Labels: enhancement

#131 fix: #103 텍스트 영역 사각형 초기화
  oot/control/low_remove_control.py
  oot/control/low_write_control.py
  oot/gui/common.py
Labels: bug

#134 Mosaic branch
  image/5.jpg
  image/6.jpg
  oot/control/low_mosaic_control.py
  oot/data/data_manager.py
  oot/gui/gui_main.py
  oot/gui/subframes/mosaic_frame.py
Labels: enhancement

#121 feat: #41 폰트 스타일 적용
  fonts/TMONBlack.ttf
  fonts/tvN 즐거운이야기 Bold.ttf
  fonts/tvN 즐거운이야기 Light.ttf
  fonts/tvN 즐거운이야기 Medium.ttf
  fonts/동그라미재단B.ttf
  fonts/동그라미재단L.ttf
  fonts/동그라미재단M.ttf
  oot/control/low_write_control.py
  oot/gui/subframes/write_frame.py
  test/jiwon/ko_font_test.py
Labels: enhancement

#137 feat: #125 쓰기탭 복원기능 구현
  oot/gui/subframes/write_frame.py
Labels: enhancement

#138 feat: 얼굴 모자이크 적용
  oot/control/low_mosaic_control.py
  oot/gui/middle_frame.py
  oot/gui/subframes/mosaic_frame.py
Labels: enhancement

#139 fix: #132 remove_tab 텍스트 지우기 정교화
  oot/gui/middle_frame.py
  test/yunjeong/grayscale.py
  test/yunjeong/grayscale_gaussian.py
Labels: bug
